# Generated by Django 4.0.8 on 2023-01-18 20:40

from django.db import migrations, models
import django.db.models.deletion
import orzu.products.instances
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to=orzu.products.instances.get_banners_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна изготовления',
                'verbose_name_plural': 'Страны изготовления',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200)),
                ('packaging_photo', sorl.thumbnail.fields.ImageField(upload_to=orzu.products.instances.get_shots_path, verbose_name='Изображение пакета')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to=orzu.products.instances.get_shots_path, verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Масса')),
                ('artikul', models.CharField(max_length=50, verbose_name='Артикул')),
                ('carbohydrates', models.FloatField(verbose_name='Углеводы')),
                ('calories', models.FloatField(verbose_name='Калории')),
                ('fats', models.FloatField(verbose_name='Жиры')),
                ('is_top', models.BooleanField(verbose_name='В топе?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='Категория продукта')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcountry', verbose_name='Страна изготовления')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'order_with_respect_to': 'category',
            },
        ),
    ]
