# Generated by Django 4.0.8 on 2023-01-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='productcountry',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание en'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание ru'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default='lorem', verbose_name='Описание uz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок en'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок ru'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_uz',
            field=models.CharField(default='lorem', max_length=100, verbose_name='Заголовок uz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcountry',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название страны en'),
        ),
        migrations.AddField(
            model_name='productcountry',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название страны ru'),
        ),
        migrations.AddField(
            model_name='productcountry',
            name='name_uz',
            field=models.CharField(default='lorem', max_length=50, verbose_name='Название страны uz'),
            preserve_default=False,
        ),
    ]
