# Generated by Django 4.0.8 on 2023-01-25 13:51

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_name_product_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='landscape_photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Альбомное фото'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
