# Generated by Django 4.0.8 on 2023-02-01 11:04

from django.db import migrations
import orzu.products.instances
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategory_landscape_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packaging_photo',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='landscape_photo',
        ),
        migrations.AddField(
            model_name='product',
            name='top_photo',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to=orzu.products.instances.get_shots_path, verbose_name='Изображение в блоке TOP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slider_photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография слайдера'),
        ),
    ]
