# Generated by Django 4.0.8 on 2023-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_packaging_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
