# Generated by Django 4.0.8 on 2023-01-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание en'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание ru'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=models.TextField(default='lorem', verbose_name='Описание uz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок en'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок ru'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(default='lorem', max_length=150, verbose_name='Заголовок uz'),
            preserve_default=False,
        ),
    ]
