name: Production Django deploy MedTour

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "."
        target: "/home/Api/orzu"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      env:
        DJANGO_SETTINGS_MODULE: "config.settings.production"
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: DJANGO_SETTINGS_MODULE
        script_stop: true
        script: |
          git --work-tree=/home/Api/orzu --git-dir=/home/Api/orzu/.git clean -f .
          /home/Api/orzu/venv/bin/pip install -r /home/Api/orzu/requirements/production.txt
          /home/Api/orzu/venv/bin/python /home/Api/orzu/manage_prod.py migrate
          /home/Api/orzu/venv/bin/python /home/Api/orzu/manage_prod.py compilemessages
          /home/Api/orzu/venv/bin/python /home/Api/orzu/manage_prod.py collectstatic --noinput
          systemctl daemon-reload
          systemctl status orzu.service
